ALTER TABLE usuario MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE produto ADD COLUMN user_id BIGINT NOT NULL;
ALTER TABLE produto MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE produto ADD CONSTRAINT fk_produto_user_id FOREIGN KEY (user_id) REFERENCES usuario(id);

ALTER TABLE servico ADD COLUMN user_id BIGINT NOT NULL;
ALTER TABLE servico MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE servico ADD CONSTRAINT fk_servico_user_id FOREIGN KEY (user_id) REFERENCES usuario(id);